---
title: "Experience"
description: |
  Dylan's intern, work, and club experience
author:
  - name: Dylan Lucko 
    url: https://dylanluckoo.com
    affiliation: The George Washington University
    affiliation_url: https://economics.columbian.gwu.edu/ma-applied-economicss
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## **EDUCATION**

### **-THE GEORGE WASHINGTON UNIVERSITY** 

**Columbian College of Arts and Sciences Bachelor(s) of Science in Economics and Statistics**; *GPA 3.77* May 2021

Relevant Coursework Includes: Portfolio Management, Multi-Variable Calculus, Econometrics, Analysis of Variance

### **-WHARTON SCHOOL ONLINE**

**Fundamentals of Quantitative Modeling-** May 2019 -- July 2019

## **EXPERIENCE**

### **-INSTITUTE FOR CORPORATE RESPONSIBILITY** 

**Researcher and Data Analyst**

Washington, D.C. \| August 2019- July 2020

-   Work closely with former SEC officials in unpacking and breaking down new regulations pertaining to the UN's Environmental & Social Goals; help companies navigate the changing regulatory space.

-   Coordinate with investors, government officials, and corporate leaders to raise necessary capital to facilitate the technological and economic development of under-served communities in Kenya, India, and Washington, D.C.

-   Research, collect, and analyze medical, political, and economic data to formulate business plans that introduce mobile hot-spotting and connectivity to the under-served communities; pitch these models to groups of investors. 

### **-HARTFORD CASWELL CAPITAL LLC.** 

**Manager- (Personal Investment Portfolio)**

Boulder, CO \| May 2017 − Present 

-   Created an LLC to better manage a personal portfolio (+373% since inception) composed of stocks and stock options;devise option trading strategies based on the relationships between different sectors; gauge movement between sectors using RSI and self-written code designed to compute correlations and synthesize trends with economic data.

### **-CONVERTPAGES** 

**Data Analyst**

New York, New York \| May 2019 − August 2019

-   Analyze data with Python to create a detailed matrix of clients and prospective clients to determine the best way market and sell the company's software.•Reach out to both existing and prospective clients via emails and cold calls to pitch and sell the software packages;write customized variations of the software for the client to be used during demonstrational phone calls.

### **-CONVERSION-FLY** 

**Financial Consultant- (Marketing Analytics Software)**

Jacksonville, Florida (Remote) \| October 2018 − May 2019 

-   Deliver financial analytics, including detailed analysis of financial statements and expenses to better gauge the flow of capital and formulate projections, ultimately reducing expenses by 2.3% thus far.

-   Synthesize the company's financial data to construct a detailed Excel model of the company's performance.

### **-SEVEN WEALTH CAPITAL** 

**Intern**

Boulder, Colorado \| July 2018 − August 2018 

-   Operated the firm's risk assessment software and used client preferences to generate risk tolerance for 20 client portfolios to ensure that each client's holdings reflected adjusted market volatility and risk aversion.

### **-LEFTY'S PIZZA** 

**Store Manager**

Niwot, Colorado \| May 2017 − August 2017 

-   Managed the finances (i.e. taxes and financial statements); boosted sales between 6% and 8% while decreasing costs by 3% by negotiating a 10-month contract with local farmers- supplying fresh produce and lowering variable costs. 

## CLUB AFFILIATIONS

### **-GW Alpha Fund**

**Founder**-Quantitative & Machine Learning Based Hedge Fund

### **-GW Socially Responsible Investment Fund** 

**Vice President of Finance, Co Founder-** (+15% 9 mo.)

### **-TAMID Investment Fund** 

**President, Fund Investment Officer-** (+24% 9 mo.)
