---
title: "Select Journalism Articles"
description: |
  A few writing samples.
author:
  - name: Dylan Lucko 
    url: https://dylanlucko.com
    affiliation: The George Washington University
    affiliation_url: https://economics.columbian.gwu.edu/ma-applied-economics
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Rodger Stone

\

 **United States v. Roger Stone**

Jurors are poised to deliberate Thursday morning after prosecutors conclude their case against political operative and strategist Roger Stone in the government's latest move in getting to the bottom of the alleged collusion in the 2016 presidential election. 

In their closing statements on Wednesday, the U.S. Attorney's Office painted Stone as a "serial liar" to jurors, who "repeatedly lied to members of Congress" during the three hours of questioning about his and the Trump Campaign's effort to find political dirt on Trump's 2016 opponent. 

"He lied not once, not twice, not three or four or five times. Stone lied over and over to the House Intelligence Committee," Assistant U.S. Attorney Johnathan Kravis told jurors Wednesday afternoon. 

Stone pleaded not guilty to a seven-count indictment, which charged him with obstruction of justice, witness tampering, and lying to the House Intelligence Committee as it investigated the 2016 election interference by Russia. 

"Stone sat before the House Intelligence Committee in 2017 to answer questions about his involvement in the Trump Campaign's procurement of stolen WikiLeaks documents," Assistant U.S. Attorney Michael Morando told jurors. "Stone participated freely but had every intention to lie about the circumstances." 

The House committee wanted to know the name of Stone's contact at WikiLeaks, whether it was an intermediary or WikiLeaks founder Julian Assange. Previously, Stone had publicly 

announced at a Trump rally that he had personally spoken to Assange and that "more documents were on the way." He now denied he ever said that. 

Stone's lies prohibited Congress from understanding how the WikiLeaks document releases unfolded and what it meant for the investigation into Russian collusion. 

In his Stone's defense, attorney Bruce Rogow told jurors that Stone had no reason to lie to protect Trump, who was by that time president. Rogow then argued that Stone's affiliation with WikiLeaks was entirely legal. 

"There was nothing illegal about the campaign being interested in information that WikiLeaks was going to be putting out," Rogow said. "This is what happens in a campaign. They look for opposition information. It happens every day; it happens in every campaign." 

Kravis refuted Rogow's argument, stating that "Because of Stone's lies, the committee never interviewed Stone's intermediaries or saw his correspondence, and their report is not accurate when it says there is no evidence that he got information from WikiLeaks." 

Stone's attorneys argued that he did not intend to lie to the House committee "because Stone thought the questions were asked only within the scope of Russian collusion." 

Kravis did not buy Rogow's argument, calling the line of logic "nonsense." The U.S. Attorney then showed jurors highlighted lines of Stone's House testimonial transcript, where he acknowledged the importance of the WikiLeaks document releases. 

"Stone's defense rests primarily on the premise of government overreach," Attorney Paul Kamenar said during a court recess. "As long as the defense can prove that Stone's lying had nothing to do with the Russian collusion, the prosecution has nothing." 

Kamenar was set to represent his client Andrew Miller, Stone's "wingman," but the defense never called Miller to the stand. Kamenar now sat in the audience as a spectator 

In his closing remarks, Morando called the jurors to action to reject Rogow's argument of complacency. 

"At the end of the day, it's a question of why it matters that we're here today," Assistant U.S. Attorney Michael Morando told jurors. "We're here today because truth matters. Roger Stone was fully aware that if any of this information got out, it would look really, really bad for his longtime friend and associate Donald Trump." 

------------------------------------------------------------------------

## Iran

 **Iranian Internet Blackouts and Economic Sanctions**

The internet trickled back to life Sunday morning after the Iranian government successfully cut off all connectivity to the country for more than a week in an attempt to curb protector behavior. 

The new wave of blackouts highlight the Treasury Department's inability to combat foreign government-led initiatives that censor and control its citizens, a tactic that is becoming "more prevalent in countries facing political unrest," Susan Aaronson said, a research professor of International Affairs at the George Washington University (GWU). 

"In early November, the Iranian government began steeply increasing the price of gasoline that led to nationwide unrest and demonstrations, including the burning of gas stations, grocery stores, and banks," Aaronson said. 

Analysts from the Atlantic Council say the internet shutdown is an attempt by the Iranian government to stop the flow of information- such as the correct price if gasoline- and to silence the violent demonstrations. 

The Treasury's Office of Foreign Assets Control (OFAC) took action against Iran's Minister of Information and Communications Technology, Mohammad Javad Azari Jahromi, for his role in the Iranian regime's widescale internet censorship- according to a statement by Treasury Secretary Steven Mnuchin. 

"Iran's leaders know that a free and open internet exposes their illegitimacy, so they seek to censor internet access to quell anti-regime protests," Mnuchin said. "We are sanctioning Jahromi 

for restricting internet access, including the restriction of popular messaging applications that help tens of millions of Iranians stay connected to each other and the outside world." 

Removing all connectivity makes communication with one another impossible, whether it's on the ground or with friends and family overseas. 

The blackouts put enormous strain on many Iranians, even outside of the country. 

"I haven't been able to talk to my family for almost two weeks now, and I have no idea if they have been hurt in any of the demonstrations," Amir Ali Aminian said in an interview last week. "I was planning on taking a flight home for the Thanksgiving break to see them, but I couldn't even buy a plane ticket home." 

Aminian, a native Iranian and freshman at the George Washington University, is among countless others who still do not know the fate of their friends and families even though the protests started weeks ago. 

Aminian turns to the U.S. government for resolve, but it is uncertain as to what power the government holds. 

"To find resolve, the U.S. government can either work through the Department of State to find an agreeable, diplomatic solution, or look for a solution of fiscal attrition with the Treasury Department," Aaronson said. "Given the current state of diplomatic talks with Iran, it is clear why the government chose to impose sanctions." 

What is not clear, however, is the effectiveness of further economic sanctions that the Treasury levies on Iranian officials. 

Economic sanctions have already crippled Iran's crucial oil exports, and the U.S. has sanctioned Iran's Supreme Leader Ayatollah Ali Khamenei and other top-ranking officials. Yet instances of internet blackouts are becoming more frequent and are lasting for extended periods. 

During protests in 2017, Iranian officials shut off 15% of connectivity throughout the country for a few hours. When protests erupted again in 2018, officials managed to shut off 60% of connectivity within the country. In last week's protests, 96% of connectivity was shut off, spanning a record eight days. 

"Iran's capabilities have progressed substantially over the past two years while the counter censorship effort has lagged," David Grier said, an Associate Professor of International Science and Technology Policy and International Affairs at GWU. "This is very worrisome for the global community." 

According to Doug Madory, the Director of Internet Analysis at Oracle, the latest incident is very unusual in scale and "much more advanced than anything we have yet to see from Iran." 

Iran is not the only country to take such drastic measures. Myanmar, China, India, Zimbabwe, Venezuela, and other nations have also previously blocked the internet and censored the content that their citizens can view. 

"The Treasury needs to find a way to better deter and prevent countries from shutting down their internet and leaving their citizens completely in the dark," Aaronson said. "It's a violation of basic human rights." 

The United Nations explicitly identified government-led internet shutdowns and censorship as a human rights violation in their June 2016 General Assembly meeting, yet the issue remains largely unsolved. 

"The Office of Foreign Assets Control must figure out a viable way to enforce the U.N.'s resolution, especially as more and more people become entirely dependent on the internet," Grier said. "It's in everyone's best interest." 

------------------------------------------------------------------------

## Treasury Department

\

**House Ways and Means Committee Brings Lawsuit Against Treasury Department**

The House's Ways and Means Committee sued the Treasury Department in July of 2019 to obtain six years of President Trump's tax returns in "the Democrats' latest push to uncover any financial malfeasance." 

"Finding out whether or not President Trump paid his taxes is a top priority for Democrats and could discredit many of the president's assertions," said Steven J. Balla, a Professor of Political Science and Public Policy at the George Washington University. "Suing the Treasury is their newest approach in obtaining Trump's returns." 

Under current tax codes, all tax returns are private information, and government officials face prosecution if they release them. However, under the same law, the Ways and Means Committee chairman can request and review any taxpayer's returns. 

According to Balla, the law creates a slippery slope for lawmakers. If Trump's returns point to malfeasance, the House committee would find difficulty prosecuting Trump, because in order to do so, "policy makers would have to release the returns as evidence." 

It would take a separate committee vote to make any returns public information. 

"Trump broke a 40-year tradition of major-party presidential candidates and presidents when he failed to release his tax returns," Professor Kirsten E. Martin said, a business law and ethics professor and researcher at the George Washington University. "Since we have never seen this before, lawmakers are going to have to establish a new precedent." 

Chairman Richard Neal (D., Mass.) asked the courts to enforce a previously filed subpoena that Secretary Mnuchin and IRS Commissioner Charles Rettig have repeatedly defied. 

Mnuchin and Rettig argued that the request was "unprecedented and outside the scope of congressional authority," according to a Treasury Department memo. 

The new lawsuit seeks a court order that would immediately require the officials to produce six years' worth of Mr. Trump's tax returns and audit records, ultimately bypassing the failed subpoena solution. 

The Committee cited Section 6103(f) of the Internal Revenue Code, which requires in mandatory terms that Treasury "shall furnish" the Committee with "any" requested tax return information, according to the code. 

"Since its passage, the Committee has routinely used Section 6103(f) for these purposes, and the Executive Branch has met its duty to comply with those requests," cited Todd Garvey, an attorney at the Congressional Research Service. "The section, though, has never been used to ensure the sitting president hand over tax returns." 

The Committee faces an uphill battle against both time and the Justice Department's stark position on the matter. 

"When the new congress takes office on Jan. 3, 2021, the entire process of requests and lawsuits would have to start over at that time," said Professor Vincy Fon, a professor of law and economics at the George Washington University. "Both sides of the aisle very well know this, and I suspect President Trump will take advantage of this and try to run out the clock." 

The Justice Department has also backed Treasury Secretary Mnuchin's refusal to hand over the tax returns. 

In a 33-page opinion released on June 14, the Office of Legal Counsel for the DOJ wrote that "Mr. Mnuchin accurately and reasonably concluded that he could not satisfy the request from Rep. Neal." 

The memo argues that the request was actually designed to make the returns public, not to oversee the performance of the Internal Revenue Service. 

"Allowing a congressional committee to dictate when Treasury must keep tax information confidential and when it must disclose such information would impermissibly intrude on executive power," the memo said. 

The Office of Legal Counsel, which is run by Mr. Engel, a Trump appointee, offers advice to the executive branch, but its guidance doesn't carry the force of law. 

The matter has since risen to the New York State Court of Appeals, where Trump's legal team argued that the Ways and Means Committees motif behind suing the Treasury for release of the tax returns was politically inspired in light of the coming election. 

------------------------------------------------------------------------

## John Forrer

 **Dr. John Forrer Loves Chocolate, as long as it's Conflict Free**

Though located only five blocks away from the United States Department of the Treasury, economists and business people like Dr. John Forrer still struggle to stay ahead of changes in economic policy as they fight for a more sustainable world. 

Crammed into a tiny office on the top floor of Duques Hall, John Forrer single-handedly runs the Institute for Corporate Responsibility (ICR), a chartered institute devoted to the research, development, and promotion of corporate sustainability and responsibility. 

"It's always an uphill battle navigating the ever-changing landscape of domestic and foreign economic policy," said Dr. Forrer in a discussion on Monday. "Every policy and piece of legislation matters to ensure proper corporate responsibility- staying ahead of the curve is vital." 

At the ICR, Dr. Forrer focuses primarily on impact investing, a branch of investment management that helps fund companies, organizations, or communities intending to generate a measurable, beneficial social or environmental impact alongside a financial return. 

On this particular day, like any other, Dr. Forrer sits back in his office chair with his leg crossed over the other. His four office walls are stacked floor to ceiling with books on trade, foreign policy, and economic sanctions. A map depicts everywhere he's been; papers of all sorts litter his desk; coffee rings stain the maple. He has a book about chocolate pulled aside. 

Published over 50 times in articles, books, book chapters, and monographs, Dr. Forrer is a leading academic and researcher at the crossroads where public policy, corporate governance, and impact investing come together. His projects take him all over the world, from Kenya to India. Today's topic, however, was chocolate. 

In an initiative that began in January, Dr. Forrer and the ICR worked closely with leading chocolate companies to ensure that the cocoa used to make the chocolate was sourced from ethically grown and ethically governed regions of the world. 

As Dr. Forrer noted, this was incredibly hard to do. 

"John has one of the toughest jobs of all, and that's convincing profit-seeking companies to invest in social and environmental change," said Cynthia Glassman, the former Commissioner of the SEC and colleague of Dr. Forrer. 

Dr. Forrer and Hon. Glassman's relationship dates back many years, to the time before President Bush appointed Hon. Glassman as the Commissioner of the SEC in 2009. Now, she helps Dr. Forrer navigate the landscape of corporate SEC regulations and Treasury policies as they try to enact social change. 

"As the Trump administration tightens the economic grip on many countries around the world, getting the green light to provide aid within these vulnerable areas becomes harder," said Dr. Forrer. 

Despite these policy changes, Dr. Forrer's efforts were primarily successful. Dr. Forrer now sits on the Atlantic Council and One Earth Future Council as an expert in public policy and economics. 

The Conflict-Free Chocolate initiative accompanies many others that occupy Forrer's desk at a given time. It's frequently difficult for his colleagues to keep up. 

"Last semester when I worked for him, it usually was pretty hard to walk into his office," said Charlotte, a fellow research assistant. "He would have to clear a path of papers off the floor just for me to reach the chair where I was supposed to sit." 

Regardless, Forrer's style works for him. He has made great strides in Sustainable Supply Chain Systems to create business partnerships that provide Wi-Fi in remote and under-served communities. 

"I hope to make impact investing a better option for more companies and investors," said Forrer. "Right now, it's too expensive for the little return investors are getting, but we're working to turn that around." 

Forrer's most recent journal articles include: "Business and Peace in the Buffer Condition" (2015), Academy Management Perspectives Vol. 29 no. 4 438-450; and "The PACO Index," (2016) with Timothy Fort, Business Horizons (Forthcoming). 

------------------------------------------------------------------------

## Cycling in the District

TicTok challenges, gardening, and baking sourdough bread kept many individuals sane when lockdowns swept across the country in the Spring of 2020. But as the cool months of March turned into summer, Americans needed a safe way to get outside and burn off some of those extra quarantine calories. Cycling quickly became the go to sport, and bikes flew off the racks bike stores across the country.

"Demand [for bikes] has increased, it's skyrocketed even...," John Churan said, a bike fitting specialist at Bicycle Pro Shop in Georgetown. "Folks found that it was a great way of getting yourself out of the apartment, and a great way to get your mind out of the house too."

John stressed that cycling in particular became popular because an individual at any skill level can pick it up, and all that's required is a bike (and helmet, of course). Even though John races his bike competitively now, he didn't learn to ride until he was 13 years old, when most kids learn when they're four or five.

"I had a traumatic experience when I first tried learning as a kid." John said. "I didn't try again until I was 13, but after that, I rode every day that summer."

John started racing his bike in college in Pennsylvania and competed against schools up and down the eastern seaboard. His favorite part about colligate racing was seeing one of his teammates in matching jerseys during a race and feeling inspired to ride his best. That same sense of comradery keeps John racing to this today.

That D.C. cycling community includes men like David Miller, a retired Air Force paratrooper.

"I turned to cycling because my knees couldn't withstand the impact anymore," David said. "Landing a parachute wearing full tactical armor plus all of your equipment is the equivalent of jumping off the roof of your house. And I did that over one-hundred times."

David first fell in love with cycling while on a trip to Costa Rica because it better allowed him to explore and experience his surroundings.

"The feeling of freedom from when I was a kid is the same now," David said. "If you see something to the right out your car window, you aren't going to stop. But I can."

When David races his bike, he prefers a style called cyclocross. Different than traditional road racing, cyclocross is a fast-paced alternative where competitors have to ride and run over obstacles throughout the course. In fact, riders are required to dismount and run at least twice throughout the race's duration. The courses David races on involve running up two flights of stairs, while carrying your bike.

"What it's about is pushing your personal comfort zone, hopefully you spent the year training and you're confident in your bike handling skills," David said. "That's what makes me a better cyclist because I'm used to riding at the limit of my physical ability but I'm also thinking about what the guy next to me is doing..."

Once again, as spring turns to summer in the District, popular riding locales like Hains Point will see a spike in cyclists riding its roads. Fortunately for the newcomers, there aren't any stairs to run up.
