---
title: "Untitled"
description: |
  A new article created using the Distill format.
author:
  - name: Dylan Lucko 
    url: https://dylanlucko.com
    affiliation: The George Washington University
    affiliation_url: https://economics.columbian.gwu.edu/ma-applied-economics
date: "`r Sys.Date()`"
output: distill::distill_article
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

\

Â **Background:**

This analysis concerns data from a subset of the 2008 American National
Election Study. There are 840 respondents in the sample with varying
characteristics, such as geographical location, aptitude towards
religious services, marital status, ethnic background, and gender. The
goal of this analysis is to determine if these varying categorical
factors influence political ideology. Additionally, the sample of 840
respondents will be analyzed to determine what proportion are moderate,
conservative, and liberal.Â 

Vernacular: liberal and democratic are used interchangeably;
conservative and republican are used interchangeably.Â 

\

**Methods:**

*Chi-Square Test of Goodness of Fit--To Test the Proportion of Moderate,
Conservative, and Liberal Respondents:*

A researcher believes that the true proportions of the respondents are
60% moderate, 20% conservative, and 20% liberal. To test whether the
researcher's alleged proportions are true, we will compare the actual
frequencies observed via the sample of 940 respondents the to the
expected frequencies. We will utilize the Chi-Square Goodness of Fit
Test for Specified Proportions. Code can be found in Appendix A:Â 

Hypotheses:Â 

H0: Ï€-hat= Ï€0Â 

Ha: Ï€-hatâ‰  Ï€0Â 

These hypotheses mean that we are testing to see if the estimated Ï€ (the
estimated population proportion) equals the population proportion quoted
by the researcher.Â 

Condition: for every cell, the expected cell count ğ¸_ğ‘–â‰¥5Â 

Interpretation: If the p-value for this test is less than alpha=0.05,
then we reject the hull hypothesis that the two proportions are equal,
meaning that the proportions are unequal.Â 

*Test for Independence-- To Test the Accuracy of the Following
Hypotheses:*

1\. Men are more likely than women to identify with the Republican
Party.Â 

2\. Southerners and Midwesterners are more likely than others to
identify with the Republican Party; northeasterners and westerners are
more likely than others to identify with the Democratic Party.Â 

3\. Married respondents are more likely than others to identify with the
Republican Party.Â 

\

The more regularly people attend religious services, the more likely
they are to identify with the Republican Party.Â 

5\. White people are less likely than others to identify with the
Democratic PartyÂ 

To test the accuracy of the hypotheses above, we will conduct a test for
independence and construct a series of contingency tables for each
categorical factor to compare the observed frequency with the expected
frequency. Based on this analysis and the interpretation of the p-value
for that specified Chi-Squared Test, we can determine if the political
ideology is dependent or independent of the categorical factor in
question.Â 

Interpretation: If the p-value for the specific test for independence is
less than alpha = 0.05, then we reject the null hypothesis: ğ»0:ğ‘ğ¹=ğ‘ğ‘€
ğ»ğ‘:ğ‘ğ¹â‰ ğ‘ğ‘€Â where ğ‘ğ¹ and ğ‘ğ¹ are the proportion of "categorical factor" who
prefer the Democrat party.Â 

**proc import datafile=("C:/users/dylan/desktop/politics.csv");**

**run;**

**proc print data =politics (obs=20);**

**run;**

**data politics2;**

set politics;Â 

if region in (**1**) then location = "Northeast";Â 

if region in (**2**) then location = "Midwest";Â 

if region in (**3**) then location = "South";Â 

if region in (**4**) then location = "West";Â 

if ideology in (**1**,**2**) then opinion = "Liberal";Â 

if ideology in (**3**,**4**,**5**) then opinion = "Moderate";Â 

if ideology in (**6**,**7**) then opinion = "Conservative";Â 

if marstat in (**1**) then status = "Married";Â 

if marstat in (**2**,**3**,**4**,**5**,**6**,**7**) then status
="Other";Â 

if relserv in (**1**,**2**) then rel= "Very Religious";Â 

if relserv in (**3**,**4**,**5**) then rel= "Moderatley Religious";Â 

if relserv in (**6**) then rel= "Not Religious";Â 

if ethnic in (**1**) then ethnicity= "Black";Â 

if ethnic in (**2**) then ethnicity= "Asian";Â 

if ethnic in (**3**) then ethnicity= "Native American";Â 

if ethnic in (**4**) then ethnicity= "Hispanic";Â 

if ethnic in (**5**) then ethnicity= "White";Â 

**run;**

**proc print data=politics2 (obs=20);**

**run;**

**proc freq data = politics2;**

tables opinion / testp=(0.2, 0.2, 0.6);Â 

**run;**

**proc format;**

value gen **1**= "Male" **2**="Female";Â 

**run;**

**proc freq data=politics2;**

tables gender\*opinion / chisq expected cellchi2;Â 

format gender gen.;Â 

**run;**

**proc gchart data = politics2;**

pie opinion/ group=gender;Â 

format gender gen.;Â 

**run;**

**proc freq data=politics2;**

tables location\*opinion / chisq expected cellchi2;Â 

**run;**

**proc gchart data = politics2;**

pie location/ group=location;Â 

**run;**

**proc freq data=politics2;**

tables status\*opinion / chisq expected cellchi2;Â 

**run;**

**proc gchart data = politics2;**

pie status/ group=opinion;Â 

**run;**

**proc freq data=politics2;**

tables rel\*opinion / chisq expected cellchi2;Â 

**run;**

**proc gchart data = politics2;**

pie rel/ group=opinion;Â 

**run;**

**proc freq data=politics2;**

tables ethnicity\*opinion / chisq expected cellchi2;Â 

**run;**

**proc gchart data = politics2;**

pie ethnicity/ group=opinion;Â 

**run;**
