---
title: "Editorial- Lange vs. California"
description: |
  An editorial about the Supreme Court Case Lange vs. California.
author:
  - name: Dylan Lucko
    url: https://dylanlucko.com
date: 05-02-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Four seconds. Four seconds was all the time Arthur Lange had to react to flashing police lights before exiting his car and walk into his garage. Oh, and by the way, it typically takes the human brain 5 seconds to fully process what it's seeing. Four seconds should not determine whether or not unwarranted search and seizure is lawful. Nor should the government allow an unwarranted search and seizure for any crime committed. 

In the late evening of an October Friday in 2016, when California Highway Patrol Officer Aaron Weikert observed Arthur Lange playing music loudly and honking repeatedly while driving, Weikert thought Lange might be impaired and gave pursuit. But Weikert did not turn his flashing lights on as he gave pursuit, he followed Lange stealthily. It wasn't until Lange was four seconds away from his garage door when Weikert remembered how to turn on his police lights. 

The next thing Lange knows, he's being arrested- in his garage- and the intent of the Fourth Amendment is confronted in the U.S. Supreme Court. 

The question in Lange v. California is whether police officers who pursue someone suspected of a misdemeanor into a home may conduct a warrantless search or seizure. It is well-established that police in "hot pursuit" of a suspected felon in public may follow that suspect into a residence. But what about police who are in "hot pursuit" of a misdemeanant? 

In the United States, misdemeanors account for 80% of American criminal dockets 2, which means that almost eight times out of 10, when a crime is committed, it's a misdemeanor. Expanding the police's authority to conduct unwarranted search and seizures for nearly every crime committed would be a massive over-reach by the government. 

Petty theft? The police can follow you into your home. Public intoxication? The police can search your things and personal effects. The "sanctity of the home," as it were, would be a distant memory of a fleeting pastime. 

What's more alarming about this governmental overreach, however, is its potential to worsen the relationship between minorities and the police, who already bear a disproportionate brunt of law enforcement. In his book David and Goliath, Malcom Gladwell contends that in order for policing to be effective (anywhere), the community must respect and find the police force legitimate. Gladwell continues to argue that when every minority has a brother or father or cousin in prison, it can be difficult to believe the system is fair or legitimate. If the system isn't fair, how can you believe that those in charge of enforcing that system will be fair and impartial in return3 ? 

Now imagine that if every time a police officer had suspicion that a minority was committing a misdemeanor, that police officer had the right to search and seize that individual's house without a warrant. The already frayed relationship between the police and minorities would be beyond repair. 

The prosecution, however, does raise an interesting argument. The United States contends that the risk of a misdemeanant evading arrest can be just as great as for a felony suspect: in both cases, "the suspect already has chosen to flee once, suggesting his willingness to take on the risks 

of flight again.4" In fact, the United States contends that a suspect's attempted escape suggests that he has committed a more serious offense than the one for which he is being pursued; in the moment, an officer may not be aware of the full scope of the crime. The prosecution goes on to argue that not granting the police force the ability to pursue without a warrant would encourage fleeing to house. 

The prosecution's argument, however, can be thinned in one of three ways. First, if Lange had actually been posing a serious threat to the community that he needed to escape into his house to prepare for it, then Weikert should have recognized that and turned on his lights sooner instead of at the last possible minute. If Lange was running from a more heinous crime, as purported, then why did Weikert wait so long to attempt to apprehend Lange? 

Second, the prosecution's entire argument rests upon the assertion that Lange was fleeing and evading the police officer. But Weikert did not signal to Lange that he was following him until four seconds before Lange entered his garage. Four seconds is not enough time to recognize that the glimpse of flashing lights behind were actually directed at you. 

Third, the ACLU assert that "requiring police to obtain a warrant in hot pursuit situations would not encourage fleeing because police can procure warrants remotely within minutes." 

The government's desire to allow unwarranted search and seizure in the case of misdemeanors would directly infringe upon the right guaranteed under the Fourth Amendment. It would serve as a massive over-reach of the government and police force and could be disproportionally concentrated upon communities that already bear the burden of excessive policing. Furthermore, these costly externalities come without novel benefits. The solutions already exist in the criminal justice system. 

"America's Massive Misdemeanor System Deepens Inequality and Burdens Low-Income Communities." Equal Justice Initiative, 29 Apr. 2020, eji.org/news/americas-massive-misdemeanor-system-deepens-inequality/\#:\~:text=Natapoff%20estimates%20that%20misdemeanors%20comprise,judges%20face%20crushing%20case%20loads. 

Dyne, Emily Van, and Matthew Tinker. "Lange v. California." Legal Information Institute, Legal Information Institute, 18 Feb. 2021, www.law.cornell.edu/supct/cert/20-18. 

Walsh, Mark. "Supreme Court Considers Warrantless Search-and-Seizure Case from California." ABA Journal, www.abajournal.com/web/article/scotus-considers-warrantless-search-and-seizure-case-from-california. 
