---
title: "Editorial- Social Media Password Laws"
description: |
  An editorial about changing social media password laws.
author:
  - name: Dylan Lucko
    url: https://dylanlucko.com
date: 05-02-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Americans work hard, maybe even a little too hard, and the scale of work-life balance is tilting pretty heavily towards the "work side." When the closing bell rings and the neon Open sign flickers out, the last thing employees want to think about is work- let alone worry about representing their company 24/7 every day of the year. A bill passed by the New York State legislature would help New York residents relax almost as much as that glass of wine after work. 

Passing New York AB 1844 would prohibit employers from requesting or requiring employees and applicants to disclose their social media log-in information for the purpose of accessing social media accounts. Passing such a law would not be unprecedented- California was the first state to pass such a policy eight years ago, and many other states have followed in their footsteps. The New York State legislature should also pass the bill to protect its citizens from the evident overreaching of the government and companies into the personal lives of employees across the state. 

Requesting or requiring employees and applicants to disclose their social media log-in information (including but not limited to passwords and usernames) adds a substantial load of stress on top of an already full load. Not only would employers be able to seen the front end of each social media platform (e.g. posts, comments, likes) but if passwords were no longer private, the employer would also have access to the account's archives, private messages, and viewing history. Whether in the office or on the clock, such a policy would require the employee to represent the company at all times. All posts, messages, comments, and likes to become subject to review and potential scrutiny by the employer, adding substantial stress to the already fragile 

work- life balance. Employers would have access to all front and back end content on all social media platforms, which could include messages with the man/woman who you like; it could include content that you've saved; it could include funny yet offensive memes that you've sent to your best friend. 

According to a study conducted by CNBC news, 26% of surveyed employees in the United States rate their stress level as 4.2/5 and altogether 70% of employees rate their stress as a 3.5/5 or higher. The South Louisiana Health Association, in concurrence with other leading health associations, cite that stress is the primary cause of many health problems, both mentally and physically. Employees do not need the added stress and anxiety that would come if employers had access to who their social media. Many working adults use social media as a way to unwind after work, and it is possible that their usage would decrease with employer intervention. Furthermore, constantly fearing termination or probation based on their online presence in and of itself induces stress and anxiety. 

Social media also hosts a place for political and religious discourse. Granting employers the ability to see behind the scenes of their employees' accounts welcomes the risk for discrimination in the workplace. Political and religious affairs are often private matters, and if a perspective employer or current employer discovers such private information, this could affect their attitude and propensity to hire somebody. Discrimination in the workplace laws make it illegal to discriminate based on religious, political, or otherwise private information. Allowing employer access to private information online would enable them to discriminate without anyone knowing about it. Your interviewer may not like that you're posting LGBTQ events and refuse to hire you. Your boss may see that you attended a Bernie Sanders rally and refuse you your next 

raise. This infringement of privacy further breaks down the work-life balance relationship and requires the submission of your private life for the image of the company. 

In some select cases, though, it would make sense for the employer to want access to the back end of individual's social media accounts. Companies want to minimize their liabilities, and when they hire a person, they incur a liability for the actions of that individual, both professionally and privately. In light of the recent riots at the US Capitol, if a company or firm could have foreseen their employee's involvement in the mob before they hired them via their social media trends, chances are they would not have hired that individual. The same can be said for excessive partying, drug use, or fringe group involvement that often appears on social media. If a firm can lower its liability, it will try to do so. Background checks and drug tests are common in the hiring process, and social media checks may very well be next on that list. 

That being said, stalking social media accounts is not the best option in the hiring process, or at least it shouldn't be. In some cases it might be useful in identifying problematic or criminal applicants, but there are better ways to identify those types of people. Maybe the hiring process needs some revamping. If employers cannot grasp the character of a person through an application, resume, cover letter, Hirevue, and multiple rounds of interviews, something must be wrong. Firm's shouldn't have to rely on social media to make informed decisions about their current or perspective employees. Though employees should be contentious of how their actions on social media might affect the firm they work for, it is a clear overstep of personal privacy to allow firms constant and unrestricted access to social media accounts. The marginal stress would be too high to justify the arduous and anxiety causing process, and firms most likely won't be learning any new information anyway.
