---
title: "Proseminar Abstract"
description: |
  Below is the abstract for my Proseminar Research Class.
author:
  - name: Dylan Lucko
    url: https://dylanlucko.com
date: 04-30-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Abstract**

In 2004, Colorado passed legislation that enacted its first ever initiative to transition 20 percent of the state's energy consumption to renewable forms of energy, which include solar, wind, geothermal, and hydroelectric. Nine years later in 2013, the state
increased its goal to 30 percent renewable energy. To accomplish this
transition, Colorado made the cost of producing carbon dioxide more expensive in the form of a tax per short ton of carbon dioxide emitted. In turn, energy prices in Colorado increased as the tax remittance shifted from firms to consumers of the electricity. Since a higher percentage of Coloradan's income was now going to pay for energy costs, individuals making less money could be disproportionately affected by this policy change. This paper investigates the distributional effects of the carbon tax policy in Colorado.
